version: "3.7"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    # use default config, or mount your own if needed
    # volumes:
    #   - ./loki-config.yml:/etc/loki/config.yml
    # command: -config.file=/etc/loki/config.yml

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./logs:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  tempo:
    image: grafana/tempo:2.5.0
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
    command: -config.file=/etc/tempo.yaml
    ports:
      - "3200:3200"

volumes:
  grafana-data:
